"""Initial schema with dictionaries, versions, fields, and annotations

Revision ID: 0cf0e9fac7fa
Revises: 
Create Date: 2025-11-09 09:44:53.776068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cf0e9fac7fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file_name', sa.String(length=500), nullable=True),
    sa.Column('source_file_size', sa.BigInteger(), nullable=True),
    sa.Column('total_records_analyzed', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dictionary_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processing_stats', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=1000), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('parent_path', sa.String(length=1000), nullable=True),
    sa.Column('nesting_level', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('semantic_type', sa.String(length=50), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_array', sa.Boolean(), nullable=False),
    sa.Column('array_item_type', sa.String(length=50), nullable=True),
    sa.Column('sample_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('null_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('distinct_count', sa.Integer(), nullable=False),
    sa.Column('cardinality_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('mean_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('median_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('std_dev', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('percentile_25', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('percentile_50', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('percentile_75', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('pii_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotations')
    op.drop_table('fields')
    op.drop_table('versions')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
